services:
  - type: web
    name: dts114-clinic-appointment-generator-docker
    env: docker
    plan: free
    rootDir: Task2/clinic_app
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: "/health"
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
